set pad_wire_necking on
bus diagonal
fanout 20
route 50
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
route 50 16
clean 10
filter 20
recorner diagonal
status_file
